### ISSUE TITLE
Cannot matching!

### ISSUE THREAD

**Issue by longnguyenQB** [Harshchourasiya/RandomChat#2]
![image](https://user-images.githubusercontent.com/76984368/214070542-11973bd8-afab-4fd5-a416-4db3433e28a8.png)
The first time I run it, I get the following error:
`django.core.exceptions.ImproperlyConfigured: The SECRET_KEY setting must not be empty.`
Then I try to fill it like this in setting: SECRET_KEY = 'dadsd'
When running with 2 browsers, the application cannot be paired with each other.

**Comment by Harshchourasiya** [comment]
Did you run redis on your system. This application use Redis Database so you must run it before running app
